// Code generated by cqlc. DO NOT EDIT.

package example

import (
	"github.com/gocql/gocql"
	"github.com/razcoen/cqlc/pkg/cqlc"
)

type Client struct {
	Session *gocql.Session
	Logger  cqlc.Logger
}

func NewClient(session *gocql.Session, logger cqlc.Logger) *Client {
	return &Client{Session: session, Logger: logger}
}
