// Code generated by cqlc. DO NOT EDIT.

package example

import (
	"github.com/gocql/gocql"
	"time"
)

type CreateUserParams struct {
	UserID    gocql.UUID
	Username  string
	Email     string
	CreatedAt time.Time
}

type CreateUserResult struct {
}

func (c *Client) CreateUser(params CreateUserParams) ([]*CreateUserResult, error) {
}

type FindUserParams struct {
	UserID gocql.UUID
}

type FindUserResult struct {
	UserID    gocql.UUID
	Username  string
	Email     string
	CreatedAt time.Time
}

func (c *Client) FindUser(params FindUserParams) ([]*FindUserResult, error) {
}
