version: 2

builds:
  - main: ./cmd/cqlc
    binary: cqlc
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version=v{{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin

dist: ./bin
