package generate

import (
	"bytes"
	"testing"

	"github.com/razcoen/cqlc/pkg/cql"
	"github.com/stretchr/testify/require"
)

func TestGoGenerator(t *testing.T) {
	tests := []struct {
		name           string
		keyspace       *cql.Keyspace
		packageName    string
		expectedErr    bool
		expectedOutput string
	}{
		{
			name:        "Empty Keyspace",
			keyspace:    &cql.Keyspace{Name: "empty_keyspace"},
			packageName: "empty",
			expectedErr: false,
			expectedOutput: `// Code generated by cqlc. DO NOT EDIT.

package empty
`,
		},
		{
			name: "Keyspace with Single Table",
			keyspace: &cql.Keyspace{
				Name: "single_table_keyspace",
				Tables: []*cql.Table{
					{
						Name: "users",
						Columns: []*cql.Column{
							{Name: "id", DataType: cql.NativeTypeUUID.IntoDataType()},
							{Name: "name", DataType: cql.NativeTypeText.IntoDataType()},
							{Name: "age", DataType: cql.NativeTypeInt.IntoDataType()},
						},
					},
				},
			},
			packageName: "single",
			expectedErr: false,
			expectedOutput: `// Code generated by cqlc. DO NOT EDIT.

package single

// Table: users
type User struct {
	ID   string
	Name string
	Age  int64
}
`,
		},
		{
			name: "Keyspace with Multiple Tables",
			keyspace: &cql.Keyspace{
				Name: "multi_table_keyspace",
				Tables: []*cql.Table{
					{
						Name: "users",
						Columns: []*cql.Column{
							{Name: "id", DataType: cql.NativeTypeUUID.IntoDataType()},
							{Name: "name", DataType: cql.NativeTypeText.IntoDataType()},
						},
					},
					{
						Name: "orders",
						Columns: []*cql.Column{
							{Name: "order_id", DataType: cql.NativeTypeUUID.IntoDataType()},
							{Name: "user_id", DataType: cql.NativeTypeUUID.IntoDataType()},
							{Name: "amount", DataType: cql.NativeTypeDecimal.IntoDataType()},
						},
					},
				},
			},
			packageName: "multi",
			expectedErr: false,
			expectedOutput: `// Code generated by cqlc. DO NOT EDIT.

package multi

// Table: users
type User struct {
	ID   string
	Name string
}

// Table: orders
type Order struct {
	OrderID string
	UserID  string
	Amount  float64
}
`,
		},
	}

	// TODO: Test all data types
	gg, err := newGoGenerator()
	require.NoError(t, err)

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			buf := &bytes.Buffer{}
			err := gg.generateKeyspace(&generateKeyspaceRequest{
				keyspace:    tt.keyspace,
				packageName: tt.packageName,
				out:         buf,
			})

			if tt.expectedErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
				require.Equal(t, tt.expectedOutput, buf.String())
			}
		})
	}
}
