// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: clqc/v1/cqlc.proto

package cqlcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generate      []*GenerateConfig      `protobuf:"bytes,1,rep,name=generate,proto3" json:"generate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_clqc_v1_cqlc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_clqc_v1_cqlc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_clqc_v1_cqlc_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetGenerate() []*GenerateConfig {
	if x != nil {
		return x.Generate
	}
	return nil
}

type GenerateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       string                 `protobuf:"bytes,1,opt,name=queries,proto3" json:"queries,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Go            *GenerateConfigGo      `protobuf:"bytes,3,opt,name=go,proto3,oneof" json:"go,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConfig) Reset() {
	*x = GenerateConfig{}
	mi := &file_clqc_v1_cqlc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfig) ProtoMessage() {}

func (x *GenerateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_clqc_v1_cqlc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfig.ProtoReflect.Descriptor instead.
func (*GenerateConfig) Descriptor() ([]byte, []int) {
	return file_clqc_v1_cqlc_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateConfig) GetQueries() string {
	if x != nil {
		return x.Queries
	}
	return ""
}

func (x *GenerateConfig) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *GenerateConfig) GetGo() *GenerateConfigGo {
	if x != nil {
		return x.Go
	}
	return nil
}

type GenerateConfigGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Out           string                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConfigGo) Reset() {
	*x = GenerateConfigGo{}
	mi := &file_clqc_v1_cqlc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConfigGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfigGo) ProtoMessage() {}

func (x *GenerateConfigGo) ProtoReflect() protoreflect.Message {
	mi := &file_clqc_v1_cqlc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfigGo.ProtoReflect.Descriptor instead.
func (*GenerateConfigGo) Descriptor() ([]byte, []int) {
	return file_clqc_v1_cqlc_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateConfigGo) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *GenerateConfigGo) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

var File_clqc_v1_cqlc_proto protoreflect.FileDescriptor

var file_clqc_v1_cqlc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6c, 0x71, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x71, 0x6c, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x71, 0x6c, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a,
	0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x33, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x71, 0x6c, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x22, 0x79, 0x0a, 0x0e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x12, 0x2e, 0x0a, 0x02, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x71, 0x6c, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x6f, 0x48, 0x00, 0x52, 0x02, 0x67, 0x6f, 0x88, 0x01, 0x01,
	0x42, 0x05, 0x0a, 0x03, 0x5f, 0x67, 0x6f, 0x22, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x42, 0x65, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x71, 0x6c, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x43, 0x71, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x0e, 0x63, 0x71, 0x6c, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x71, 0x6c,
	0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x43, 0x71, 0x6c, 0x63,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x07, 0x43, 0x71, 0x6c, 0x63, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x13,
	0x43, 0x71, 0x6c, 0x63, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x43, 0x71, 0x6c, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clqc_v1_cqlc_proto_rawDescOnce sync.Once
	file_clqc_v1_cqlc_proto_rawDescData = file_clqc_v1_cqlc_proto_rawDesc
)

func file_clqc_v1_cqlc_proto_rawDescGZIP() []byte {
	file_clqc_v1_cqlc_proto_rawDescOnce.Do(func() {
		file_clqc_v1_cqlc_proto_rawDescData = protoimpl.X.CompressGZIP(file_clqc_v1_cqlc_proto_rawDescData)
	})
	return file_clqc_v1_cqlc_proto_rawDescData
}

var file_clqc_v1_cqlc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clqc_v1_cqlc_proto_goTypes = []any{
	(*Config)(nil),           // 0: cqlc.v1.Config
	(*GenerateConfig)(nil),   // 1: cqlc.v1.GenerateConfig
	(*GenerateConfigGo)(nil), // 2: cqlc.v1.GenerateConfigGo
}
var file_clqc_v1_cqlc_proto_depIdxs = []int32{
	1, // 0: cqlc.v1.Config.generate:type_name -> cqlc.v1.GenerateConfig
	2, // 1: cqlc.v1.GenerateConfig.go:type_name -> cqlc.v1.GenerateConfigGo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_clqc_v1_cqlc_proto_init() }
func file_clqc_v1_cqlc_proto_init() {
	if File_clqc_v1_cqlc_proto != nil {
		return
	}
	file_clqc_v1_cqlc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clqc_v1_cqlc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clqc_v1_cqlc_proto_goTypes,
		DependencyIndexes: file_clqc_v1_cqlc_proto_depIdxs,
		MessageInfos:      file_clqc_v1_cqlc_proto_msgTypes,
	}.Build()
	File_clqc_v1_cqlc_proto = out.File
	file_clqc_v1_cqlc_proto_rawDesc = nil
	file_clqc_v1_cqlc_proto_goTypes = nil
	file_clqc_v1_cqlc_proto_depIdxs = nil
}
