// Code generated by cqlc. DO NOT EDIT.
// cqlc version: (devel)
// schema: ../../testdata/alteringmigrations
// queries: ../../testdata/altering_migrations_queries.cql

package alteringmigrations

import (
	"fmt"

	"github.com/gocql/gocql"
	"github.com/razcoen/cqlc/pkg/gocqlc"
)

type Client struct {
	gocqlc.Client
}

func NewClient(session *gocql.Session, opts ...gocqlc.ClientOption) (*Client, error) {
	client, err := gocqlc.NewClient(session, opts...)
	if err != nil {
		return nil, fmt.Errorf("new client: %w", err)
	}
	return &Client{Client: *client}, nil
}
