title: cqlc
description: cqlc is a tool designed to simplify working with Cassandra databases by generating type-safe code from CQL queries.
baseurl: "/cqlc"
url: "https://razcoen.github.io"
github_username: razcoen
theme: just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
defaults:
  - scope:
      path: "."
      type: "pages"
    values:
      layout: "default"
color_scheme: light
search:
  focus_shortcut_key: "k"
# TODO: Logo
# logo: "/assets/images/just-the-docs.png"
# favicon_ico: "/assets/images/favicon.ico"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/razcoen/cqlc"
gh_edit_branch: "master"
gh_edit_source: "/docs"
gh_edit_view_mode: "tree"
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
heading_anchors: true
enable_copy_code_button: true
permalink: pretty
aux_links:
  "cqlc on GitHub":
    - "https://github.com/razcoen/cqlc"
nav_external_links:
  - title: cqlc on GitHub
    url: https://github.com/razcoen/cqlc
nav_error_report: true
liquid:
  error_mode: strict
  strict_filters: true
back_to_top: true
back_to_top_text: "Back to top"
footer_content: 'Copyright &copy; 2024-2025 Raz Cohen. Distributed by an <a href="https://github.com/razcoen/cqlc/tree/main/LICENSE.txt">MIT license.</a>'
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
