# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: cqlc
description: cqlc is a tool designed to simplify working with Cassandra databases by generating type-safe code from CQL queries.
baseurl: "/cqlc"
url: "https://razcoen.github.io"
github_username: razcoen

theme: just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

search:
  focus_shortcut_key: "k"
# TODO: Logo
# logo: "/assets/images/just-the-docs.png"
# favicon_ico: "/assets/images/favicon.ico"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/razcoen/cqlc" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: "/docs" # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

color_scheme: light

defaults:
  - scope:
      path: "."
      type: "pages"
    values:
      layout: "default"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

heading_anchors: true
enable_copy_code_button: true
permalink: pretty

aux_links:
  "cqlc on GitHub":
    - "https://github.com/razcoen/cqlc"

nav_external_links:
  - title: cqlc on GitHub
    url: https://github.com/razcoen/cqlc

nav_error_report: true

liquid:
  error_mode: strict
  strict_filters: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024-2025 Raz Cohen. Distributed by an <a href="https://github.com/razcoen/cqlc/tree/main/LICENSE.txt">MIT license.</a>'

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
